import simscape.battery.builder.*;

cell_param = ev_pack_cell_parameters();

batteryCell = Cell();
batteryCell.Geometry = PouchGeometry();

batteryCell.CellModelOptions.CellModelBlockPath="batt_lib/Cells/Battery Equivalent Circuit";
batteryCell.CellModelOptions.BlockParameters.RCPairs="rc1";
batteryCell.CellModelOptions.BlockParameters.ThermalModel = "LumpedThermalMass";

pSet = ParallelAssembly(Cell=batteryCell,NumParallelCells=2,...
    Topology="SingleStack",Rows=1, ModelResolution="Detailed");
module = Module(ParallelAssembly=pSet, ...
    NumSeriesAssemblies=6, ...
    ModelResolution="Detailed", ...
    CellParameterVariation="PercentDeviation");

moduleAssembly = ModuleAssembly(Module=repmat(module,1,32), ...
    AmbientThermalPath="CellBasedThermalResistance");
%pack = Pack("ModuleAssembly",repmat(moduleAssembly,1,1), ...
%    AmbientThermalPath="CellBasedThermalResistance");
%batteryChart(moduleAssembly)

buildBattery(moduleAssembly,LibraryName="thermalCoupledCellResolution",Directory="./",...
            MaskInitialTargets="VariableNames" ,...
            MaskParameters="VariableNamesByInstance", Verbose="on")

% buildBattery(moduleAssembly,LibraryName="thermalCoupledCellResolution",Directory="./",...
%             MaskInitialTargets="VariableNamesByInstance",...
%             MaskParameters="VariableNamesByInstance")